server:
  port: 8183

spring:
  application:
    name: bank-service

logging:
  level:
    ROOT: info

service:
  swagger:
    host: localhost:8183

services:
  account-service-url: http://localhost:8182/account-service
